# These are the subgraphs in this supergraph
# They are deployed first, so they're running in the environment

# When the subgraphs are ready to serve requests
# we publish the subgraph schemas to the Apollo Registry

# Apollo Registry then does:
# - supergraph CI: composes the subgraphs into a supergraph schema
# - supergraph CD: feeds new supergraph schema to the Apollo Router via Apollo Uplink polling every few seconds

# Run 'make demo' to get started
# then run 'make smoke' in separate window
# or open http://localhost:4000 to use Apollo Sandbox to issue queries

# Note this is the base docker-compose file for this project.
# The paths in all other compose files are **relative to this file**, per:
# https://docs.docker.com/compose/extends/#multiple-compose-files

# see `./opentelemetry` `./misc/studio` and `./misc/local` for other compose files

version: '1.0'
services:
  stripe_customers:
    container_name: stripe-customers
    build: ./subgraphs/stripe-customers
    ports:
      - '4001:4000'
  stripe_intents:
    container_name: stripe-intents
    build: ./subgraphs/stripe-intents
    ports:
      - '4002:4000'
